In [4]:
# Import torch and check if successful by verifying version
import torch
torch.__version__

'2.12.0+cpu'

In [7]:
# Scalar
scalar = torch.tensor(7)
print(scalar,scalar.ndim,scalar.item())

tensor(7) 0 7


In [8]:
# Vector
vector = torch.tensor([7,7])
print(vector,vector.ndim,vector.shape)

tensor([7, 7]) 1 torch.Size([2])


In [12]:
# Matrix - normally capitalised
MATRIX = torch.tensor([[7,8], 
                       [9,10]])
print(MATRIX.ndim,",",MATRIX.shape)

2 , torch.Size([2, 2])


In [ ]:
# Tensor - normally capitalised
TENSOR = torch.tensor([[[1,2,3]
                        [3,6,9]
                        [2,4,5]]])
# Check dimensions and shape of tensor
print(TENSOR.ndim,",",TENSOR.shape

In [14]:
# Creating random tensors of certain sizing
rand_tensor = torch.rand(size=(3,4))
rand_tensor, rand_tensor.dtype

(tensor([[0.1721, 0.9768, 0.9223, 0.4686],
         [0.1551, 0.3320, 0.3937, 0.3153],
         [0.0207, 0.8569, 0.7735, 0.9629]]),
 torch.float32)

In [15]:
# Zero tensors
zeros =  torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
# Tensor of ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [19]:
# Creating range of numbers 0-40 in 10's
first_40 = torch.arange(start=0, end=50, step=10)
first_40

tensor([ 0, 10, 20, 30, 40])

In [21]:
# Copy shape and load with new values - use previous tensor
zeroed_first_40 = torch.zeros_like(input=first_40)
zeroed_first_40


tensor([0, 0, 0, 0, 0])

In [24]:
# Check where tensor is stored
new_tensor = torch.rand(2,3)
print(new_tensor)
print(f"This tensor is stored on: {new_tensor.device}, with datatype: {new_tensor.dtype}")

tensor([[0.6406, 0.3818, 0.1783],
        [0.1309, 0.2307, 0.2937]])
This tensor is stored on: cpu, with datatype: torch.float32
