In [5]:
import torch

In [6]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
add_to_tensor = tensor+10
multiply_tensor = tensor*10 # Can also use -> torch.multiply(tensor,10)
# Reassign original tensor
tensor = tensor+10
# Print all three results
print(add_to_tensor, multiply_tensor,tensor)

tensor([11, 12, 13]) tensor([10, 20, 30]) tensor([11, 12, 13])


In [11]:
# Element-wise and Matrix Multiplication
my_tensor = torch.tensor([1,2,3])
# Element-wise matrix multiplication
tensor_result1 = my_tensor*my_tensor
# Matrix multiplication
tensor_result2 = torch.matmul(my_tensor,my_tensor)
tensor_result3 = torch.matmul
print(tensor_result1, tensor_result2)

tensor([1, 4, 9]) tensor(14)


In [23]:
# Perform Transpose on Matrix to allow multiplication of same sizes
new_tensor1 = torch.tensor([[1,2],
                            [3,4],
                            [5,6]], dtype=torch.float32)

new_tensor2 = torch.tensor([[7,10],
                            [8,11],
                            [9,12]], dtype=torch.float32)
print(new_tensor2.T)

result_tensor = torch.matmul(new_tensor1, new_tensor2.T)
print(result_tensor)


tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [26]:
# Using the linear module (feed-forward/fully connected layer)
# Implements a Matrix multiplication between input x and a weights matrix a
# x - input to the layer, A - is the weights created by the layer (starts as random and iteratively changes/improves hopefully!)
# b - is the bias term used as an offset for the weights and inputs, y - is output (manipulated input aiming to detect patterns)
# Linear layer starts with random values
torch.manual_seed(42)
# Next step uses matrix multiplication
linear = torch.nn.Linear(in_features=2,  # Matches inner dimensions of input
                         out_features=6) # describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [31]:
# Data Aggregation techniques (mean,min,max,sum,etc)
# Create reference tensor
x = torch.arange(0,100,10)
print(x)
print(x.min(),x.max(),x.type(torch.float32).mean(),x.sum()) # mean requires the values to be set as float32 to work
print(torch.min(x),torch.max(x),torch.mean(x.type(torch.float32)),torch.sum(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(90) tensor(45.) tensor(450)
tensor(0) tensor(90) tensor(45.) tensor(450)


In [34]:
# Finding position of min.max values within a tensor
tensor_C = torch.arange(0,100,10)
print(tensor_C)
print(tensor_C.argmin(),tensor_C.argmax())


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(9)


In [41]:
# Changing or creating new tensor with different type used
tensor_float32 = torch.arange(10.,100.,5.)
print(tensor_float32.dtype)
tensor_float16 = tensor_float32.type(torch.float16)
print(tensor_float16.dtype)

torch.float32
torch.float16
